# Minecraft version config
mc_version=26.1.2
server_jar_url=https://piston-data.mojang.com/v1/objects/97ccd4c0ed3f81bbb7bfacddd1090b0c56f9bc51/server.jar
vineflower_url=https://github.com/Vineflower/vineflower/releases/download/1.12.0/vineflower-1.12.0.jar

# Java
org.gradle.java.installations.auto-detect=true
